// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/reversi.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class ReversiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ReversiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ReversiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// 取得可以下的位置
  ffi.Pointer<PairArray> getMovableArray(
    int player,
    ffi.Pointer<IntArray> chessTable,
  ) {
    return _getMovableArray(
      player,
      chessTable,
    );
  }

  late final _getMovableArrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<PairArray> Function(
              ffi.Int, ffi.Pointer<IntArray>)>>('getMovableArray');
  late final _getMovableArray = _getMovableArrayPtr.asFunction<
      ffi.Pointer<PairArray> Function(int, ffi.Pointer<IntArray>)>();

  /// 落子
  ffi.Pointer<IntArray> makeMove(
    int player,
    ffi.Pointer<IntArray> chessTable,
    ffi.Pointer<PairStruct> dropPoint,
  ) {
    return _makeMove(
      player,
      chessTable,
      dropPoint,
    );
  }

  late final _makeMovePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<IntArray> Function(ffi.Int, ffi.Pointer<IntArray>,
              ffi.Pointer<PairStruct>)>>('makeMove');
  late final _makeMove = _makeMovePtr.asFunction<
      ffi.Pointer<IntArray> Function(
          int, ffi.Pointer<IntArray>, ffi.Pointer<PairStruct>)>();

  /// 可以吃的棋
  ffi.Pointer<PairArray> getAllCanFlipped(
    int player,
    ffi.Pointer<IntArray> chessTable,
  ) {
    return _getAllCanFlipped(
      player,
      chessTable,
    );
  }

  late final _getAllCanFlippedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<PairArray> Function(
              ffi.Int, ffi.Pointer<IntArray>)>>('getAllCanFlipped');
  late final _getAllCanFlipped = _getAllCanFlippedPtr.asFunction<
      ffi.Pointer<PairArray> Function(int, ffi.Pointer<IntArray>)>();

  /// 使用Random的AI (Level 1)
  ffi.Pointer<IntArray> aiRandom(
    int player,
    ffi.Pointer<IntArray> chessTable,
  ) {
    return _aiRandom(
      player,
      chessTable,
    );
  }

  late final _aiRandomPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<IntArray> Function(
              ffi.Int, ffi.Pointer<IntArray>)>>('aiRandom');
  late final _aiRandom = _aiRandomPtr
      .asFunction<ffi.Pointer<IntArray> Function(int, ffi.Pointer<IntArray>)>();

  /// 使用貪婪演算法的AI (Level 2)
  ffi.Pointer<IntArray> aiGreedy(
    int player,
    ffi.Pointer<IntArray> chessTable,
  ) {
    return _aiGreedy(
      player,
      chessTable,
    );
  }

  late final _aiGreedyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<IntArray> Function(
              ffi.Int, ffi.Pointer<IntArray>)>>('aiGreedy');
  late final _aiGreedy = _aiGreedyPtr
      .asFunction<ffi.Pointer<IntArray> Function(int, ffi.Pointer<IntArray>)>();

  /// 使用貪婪+位置權重+吃子數量的AI (Level 3)
  ffi.Pointer<IntArray> aiGreedyAlphaBeta(
    int player,
    ffi.Pointer<IntArray> chessTable,
  ) {
    return _aiGreedyAlphaBeta(
      player,
      chessTable,
    );
  }

  late final _aiGreedyAlphaBetaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<IntArray> Function(
              ffi.Int, ffi.Pointer<IntArray>)>>('aiGreedyAlphaBeta');
  late final _aiGreedyAlphaBeta = _aiGreedyAlphaBetaPtr
      .asFunction<ffi.Pointer<IntArray> Function(int, ffi.Pointer<IntArray>)>();

  /// 釋放記憶體
  void freePairArray(
    ffi.Pointer<PairArray> pairArray,
  ) {
    return _freePairArray(
      pairArray,
    );
  }

  late final _freePairArrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PairArray>)>>(
          'freePairArray');
  late final _freePairArray =
      _freePairArrayPtr.asFunction<void Function(ffi.Pointer<PairArray>)>();

  void freeIntArray(
    ffi.Pointer<IntArray> intArray,
  ) {
    return _freeIntArray(
      intArray,
    );
  }

  late final _freeIntArrayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<IntArray>)>>(
          'freeIntArray');
  late final _freeIntArray =
      _freeIntArrayPtr.asFunction<void Function(ffi.Pointer<IntArray>)>();
}

final class IntArray extends ffi.Struct {
  external ffi.Pointer<ffi.Int> array;

  @ffi.Int()
  external int size;
}

final class PairStruct extends ffi.Struct {
  @ffi.Int()
  external int first;

  @ffi.Int()
  external int second;
}

final class PairArray extends ffi.Struct {
  external ffi.Pointer<PairStruct> array;

  @ffi.Int()
  external int size;
}

enum Player {
  None(0),
  Black(1),
  White(2);

  final int value;
  const Player(this.value);

  static Player fromValue(int value) => switch (value) {
        0 => None,
        1 => Black,
        2 => White,
        _ => throw ArgumentError("Unknown value for Player: $value"),
      };
}
